# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

"""Template for the POSIX-shell hook wrapper Gerrit invokes.

Gerrit's ``hooks`` plugin execs whatever it finds in
``/var/gerrit/hooks/<hook-name>``.  Rather than symlinking straight
to the ``gerrit_to_platform`` console script we install a small
wrapper so every dispatch attempt is recorded in a single log file.
The wrapper is a large, carefully quoted shell literal, so it lives
in its own module to keep the setup steps readable.

Usage::

    from g2p_hook_wrapper import build_hook_wrapper

    body = build_hook_wrapper("patchset-created", "/opt/x/bin/foo")
"""

from __future__ import annotations

from g2p_paths import G2P_HOOK_LOG


def build_hook_wrapper(hook_name: str, target_bin: str) -> str:
    """Build the POSIX-shell wrapper installed in /var/gerrit/hooks/.

    The wrapper is intentionally tiny and dependency-free so it works
    in any minimal container environment.  For each Gerrit hook
    invocation it:

    * Records a structured header line carrying timestamp, hook
      name, PID, and the full argv so the wider operational log
      can be sliced per-event.
    * Forwards stdout and stderr from the underlying console script
      back to Gerrit's hooks plugin (the plugin captures these for
      its own logging) **and** appends a copy to ``G2P_HOOK_LOG``
      so a single ``tail -F`` shows every dispatch attempt.
    * Captures the exit code, prints a footer line, and re-exits
      with the same code so Gerrit's hook accounting is unchanged.

    Parameters
    ----------
    hook_name:
        The Gerrit hook name (e.g. ``patchset-created``).
    target_bin:
        Absolute path to the underlying ``gerrit_to_platform``
        console script that the wrapper should invoke.

    Returns
    -------
    str
        The wrapper script contents (UTF-8 text).  The caller is
        responsible for writing it to the container with mode 0755.
    """
    # NOTE: keep this script /bin/sh-compatible (no bashisms).  The
    # base Gerrit image ships a minimal shell environment for the
    # gerrit user.  Use single-quoted heredoc so Python f-string
    # interpolation is restricted to {hook_name}/{target_bin}/{log}
    # and shell variables like $$ are passed through verbatim.
    log = G2P_HOOK_LOG
    return f"""#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation
#
# Auto-generated by gerrit-action: G2P hook wrapper for {hook_name}.
# Do not edit by hand — it will be overwritten on the next deploy.
#
# Logs every invocation to {log} so operators can confirm whether
# Gerrit's 'hooks' plugin fires this hook for real events and what
# the underlying gerrit_to_platform console script returned.
set -u

HOOK_NAME='{hook_name}'
TARGET='{target_bin}'
LOG='{log}'

# ISO-8601 UTC timestamp; falls back to a POSIX-portable form if
# the runtime busybox/coreutils variant lacks --iso-8601=seconds.
_ts() {{
    date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date -u
}}

start_ts=$(_ts)
pid=$$

# Header: timestamp, hook, pid, full argv.  Each argv element is
# wrapped in single quotes with any embedded single quotes
# replaced by the standard POSIX-shell quoting sequence
# ``'\''`` (close, escaped quote, reopen) via two sed substitutions.
# This is functionally equivalent to printf %q without depending
# on bash, so embedded spaces and special characters survive the
# round-trip into the log file in a form a human reader can
# unambiguously re-tokenise.
{{
    printf '%s [g2p-hook][%s] start pid=%s argv:' "$start_ts" "$HOOK_NAME" "$pid"
    for a in "$@"; do
        printf ' %s' "$(printf '%s' "$a" | sed -e "s/'/'\\\\''/g" -e "s/^/'/; s/$/'/")"
    done
    printf '\n'
}} >> "$LOG" 2>/dev/null || true

# Run the underlying console script.  The wrapper preserves the
# Gerrit hook contract by re-emitting stdout on stdout and stderr
# on stderr (a previous version merged the two via 2>&1, which
# would confuse anything downstream that distinguishes the two
# streams).  We capture each stream to its own temp file, replay
# them on the matching fd, then append both to the persistent
# log with a per-line prefix so the log stays greppable per-hook.
#
# Require ``mktemp``: a predictable fallback (e.g. /tmp/g2p-hook-$$)
# is a symlink/clobber risk on multi-tenant hosts.  If mktemp is
# unavailable we exit with rc=70 (EX_SOFTWARE) and a clear message
# rather than silently using a guessable path.
out_tmp=$(mktemp 2>/dev/null) || {{
    printf '%s [g2p-hook][%s][pid=%s] mktemp unavailable; ' \
        "$(_ts)" "$HOOK_NAME" "$pid" >&2
    printf 'cannot safely capture hook output, aborting\n' >&2
    printf '%s [g2p-hook][%s] end pid=%s rc=70 (mktemp missing)\n' \
        "$(_ts)" "$HOOK_NAME" "$pid" >> "$LOG" 2>/dev/null || true
    exit 70
}}
err_tmp=$(mktemp 2>/dev/null) || {{
    rm -f "$out_tmp"
    printf '%s [g2p-hook][%s][pid=%s] mktemp unavailable; ' \
        "$(_ts)" "$HOOK_NAME" "$pid" >&2
    printf 'cannot safely capture hook output, aborting\n' >&2
    printf '%s [g2p-hook][%s] end pid=%s rc=70 (mktemp missing)\n' \
        "$(_ts)" "$HOOK_NAME" "$pid" >> "$LOG" 2>/dev/null || true
    exit 70
}}
"$TARGET" "$@" >"$out_tmp" 2>"$err_tmp"
rc=$?

# Replay each captured stream on the matching fd back to Gerrit's
# hook plugin.  The plugin gets the same per-stream bytes it would
# have received if our wrapper were not in the path at all.
cat "$out_tmp"
cat "$err_tmp" >&2

# Append both streams to the persistent log with a per-line tag
# that records which stream the line came from, so post-mortem
# readers can still tell stdout from stderr.
if [ -s "$out_tmp" ]; then
    sed -e "s|^|$(_ts) [g2p-hook][$HOOK_NAME][pid=$pid][out] |" "$out_tmp" \
        >> "$LOG" 2>/dev/null || true
fi
if [ -s "$err_tmp" ]; then
    sed -e "s|^|$(_ts) [g2p-hook][$HOOK_NAME][pid=$pid][err] |" "$err_tmp" \
        >> "$LOG" 2>/dev/null || true
fi
rm -f "$out_tmp" "$err_tmp"

end_ts=$(_ts)
printf '%s [g2p-hook][%s] end pid=%s rc=%s\n' "$end_ts" "$HOOK_NAME" "$pid" "$rc" \
    >> "$LOG" 2>/dev/null || true

exit "$rc"
"""
