# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

"""Pure renderers for the g2p configuration text artefacts.

These functions turn a validated :class:`G2PConfig` into the exact
text that later gets deployed into the Gerrit container.  They touch
neither Docker nor the filesystem, which keeps the interesting
formatting rules (case-sensitive INI keys, the platform-detection
remote stanza) independently testable.

Usage::

    from g2p_config import G2PConfig
    from g2p_ini import generate_g2p_ini

    print(generate_g2p_ini(G2PConfig.from_environment()))
"""

from __future__ import annotations

import configparser
from io import StringIO

from g2p_config import G2PConfig


def generate_g2p_ini(config: G2PConfig) -> str:
    """Produce the ``gerrit_to_platform.ini`` file content.

    Parameters
    ----------
    config:
        A validated :class:`G2PConfig` instance.

    Returns
    -------
    str
        INI-formatted string ready to write to disk.
    """
    cp = configparser.ConfigParser()
    # Preserve key case (comment keywords are case-sensitive).
    cp.optionxform = str  # type: ignore[assignment]

    # -- comment-added keyword mappings ----------------------------------
    section = 'mapping "comment-added"'
    cp.add_section(section)
    for keyword, workflow_filter in config.comment_mappings.items():
        cp.set(section, keyword, workflow_filter)

    # -- GitHub token ----------------------------------------------------
    if config.github_token:
        cp.add_section("github.com")
        cp.set("github.com", "token", config.github_token)

    buf = StringIO()
    cp.write(buf)
    return buf.getvalue()


def generate_g2p_replication_section(config: G2PConfig) -> str:
    """Generate the replication config section for g2p platform detection.

    This section does **not** replicate data.  It exists solely so that
    ``gerrit_to_platform`` can detect the GitHub platform, owner, and
    repository naming convention by reading the replication config.

    Parameters
    ----------
    config:
        A validated :class:`G2PConfig` instance.

    Returns
    -------
    str
        INI-style config lines to append to ``replication.config``.
    """
    url = config.effective_remote_url
    if not url:
        return ""

    lines = [
        "",
        "# G2P platform detection remote (not for replication)",
        "# Auto-generated by gerrit-action",
        '[remote "github-g2p"]',
        f"  url = {url}",
        f"  authGroup = {config.remote_auth_group}",
        f"  remoteNameStyle = {config.remote_name_style}",
        "",
    ]
    return "\n".join(lines)
