# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

"""Rendering the pull-replication plugin's ``replication.config``.

This module owns the text of the file that tells the pull-replication
plugin what to fetch: the remotes, their refspecs and their tuning
knobs (:func:`render_replication_config`).

The matching credentials live in :mod:`startup_secure_config`, and the
two must stay in lock-step — every remote section emitted here needs a
corresponding credential section there, or the plugin silently falls
back to anonymous auth.

Nothing here talks to Docker or to the network — the functions take a
description of the source Gerrit plus the action config and write a
file, which keeps the (security-critical) refspec rules readable and
testable on their own.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

from config import ActionConfig

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ReplicationSource:
    """How to reach the upstream Gerrit that an instance replicates from.

    Bundles the four coordinates that together identify the source
    server and the transport used to clone from it.  They are always
    resolved and passed as a set, so naming them as one value keeps
    the rendering functions honest about what they need.

    Attributes
    ----------
    host:
        Hostname of the remote Gerrit server.
    ssh_user:
        Username for SSH-based replication.
    ssh_port:
        SSH port of the remote Gerrit server.
    api_path:
        Detected REST API path prefix (e.g. ``"/r"``), used to build
        HTTP replication URLs.
    """

    host: str
    ssh_user: str
    ssh_port: int
    api_path: str

    def git_url(self, auth_type: str) -> str:
        """Return the ``${name}``-templated git URL for *auth_type*."""
        if auth_type.lower() == "ssh":
            return f"ssh://{self.ssh_user}@{self.host}:{self.ssh_port}/${{name}}.git"

        # HTTP-based auth uses /a/ prefix for authenticated access
        path = self.api_path.strip("/")
        if path:
            return f"https://{self.host}/{path}/a/${{name}}.git"
        return f"https://{self.host}/a/${{name}}.git"


def render_replication_config(
    config_file: Path,
    slug: str,
    source: ReplicationSource,
    project: str,
    config: ActionConfig,
) -> None:
    """Generate ``replication.config`` for the pull-replication plugin.

    The generated config uses ``fetchEvery`` for polling-based
    replication rather than ``apiUrl`` (the two are mutually exclusive).
    """
    git_url = source.git_url(config.auth_type)

    lines = _preamble_lines(config)
    lines.extend(_primary_remote_lines(slug, git_url, project, config))
    if config.replicate_meta_refs:
        lines.extend(_magic_repo_remote_lines(slug, git_url, config))

    config_file.parent.mkdir(parents=True, exist_ok=True)
    config_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _preamble_lines(config: ActionConfig) -> list[str]:
    """Return the file header plus the global ``[gerrit]``/``[replication]``."""
    return [
        "# Pull-replication configuration",
        "# Auto-generated by gerrit-server-action",
        "#",
        "# This configuration uses fetchEvery for polling-based replication.",
        "# The plugin will poll the source Gerrit at the configured interval",
        "# to fetch any new or changed refs.",
        "",
        "[gerrit]",
        f"  replicateOnStartup = {str(config.sync_on_startup).lower()}",
        "  autoReload = true",
        "",
        "[replication]",
        "  lockErrorMaxRetries = 5",
        "  maxRetries = 5",
        "  useCGitClient = false",
        "  refsBatchSize = 50",
        "",
    ]


def _remote_tuning_lines(
    config: ActionConfig,
    *,
    create_missing: bool,
    replicate_hidden: bool,
) -> list[str]:
    """Return the timeout/retry/thread settings shared by every remote."""
    # Calculate connection timeout (at least 2 minutes, in milliseconds)
    timeout_ms = config.replication_timeout * 1000
    connection_timeout_ms = max(timeout_ms, 120_000)

    return [
        f"  timeout = {config.replication_timeout}",
        f"  connectionTimeout = {connection_timeout_ms}",
        "  replicationDelay = 0",
        "  replicationRetry = 60",
        f"  threads = {config.replication_threads}",
        f"  createMissingRepositories = {str(create_missing).lower()}",
        f"  replicateHiddenProjects = {str(replicate_hidden).lower()}",
    ]


def _sync_refspecs(config: ActionConfig) -> list[str]:
    """Return the per-project fetch refspecs for the primary remote."""
    sync_refs = [r.strip() for r in config.sync_refs.split(",") if r.strip()]

    # When meta-ref replication is enabled, append the per-project
    # refspecs that carry NoteDb change metadata (``refs/changes/*``
    # already covers ``refs/changes/NN/CCCCCC/meta`` by hierarchy)
    # and per-project ACL / dashboard config (``refs/meta/config``,
    # ``refs/meta/dashboards`` etc.) plus the merge-preview cache.
    # (Account/group-scoped NoteDb refs such as
    # ``refs/meta/external-ids`` live on ``All-Users`` — not on
    # normal per-project repos — and are fetched by the dedicated
    # ``<slug>-meta`` remote, not by this per-project wildcard.)
    # Duplicates are tolerated by Gerrit but suppressed here so the
    # generated file stays tidy when an operator already lists the
    # ref pattern explicitly in ``sync_refs``.
    #
    # Note: the per-project remote DOES mirror each project's own
    # ``refs/meta/config`` (via the ``refs/meta/*`` wildcard).  This
    # is intentional and is a different trade-off from the magic-repo
    # remote's handling:
    #
    # * Per-project ``refs/meta/config`` defines that project's
    #   *project-local* ACL (per-ref read / push / submit
    #   permissions, plus the project's owner-group reference).
    # * The bootstrap container does not have a meaningful local
    #   ACL for replicated user projects (they were just pre-
    #   created as empty bare repos by ``fetch_and_precreate_
    #   projects``), so mirroring the source's ACL is a strict
    #   improvement: it lets the deployed Gerrit reflect the
    #   source server's per-project access rules.
    # * The bootstrap admin account 1000000 retains the global
    #   ``administrateServer`` capability (because the magic-repo
    #   remote excludes ``All-Projects:refs/meta/config`` — see the
    #   block comment in :func:`_magic_repo_remote_lines`), and that
    #   capability bypasses project-level ACLs, so the admin still
    #   sees every replicated project regardless of what its
    #   per-project ACL says.
    # * Non-admin / anonymous viewers may be blocked by per-project
    #   ACLs that reference source-server group UUIDs that do not
    #   exist locally, but that is the expected behaviour for a
    #   "mirror the source server" deployment shape.
    if config.replicate_meta_refs:
        for extra in (
            "+refs/meta/*:refs/meta/*",
            "+refs/cache-automerge/*:refs/cache-automerge/*",
        ):
            if extra not in sync_refs:
                sync_refs.append(extra)

    return sync_refs


def _primary_remote_lines(
    slug: str,
    git_url: str,
    project: str,
    config: ActionConfig,
) -> list[str]:
    """Return the ``[remote "<slug>"]`` section for user projects."""
    lines = [
        f'[remote "{slug}"]',
        f"  url = {git_url}",
    ]

    if config.fetch_every_enabled:
        lines.append(f"  fetchEvery = {config.fetch_every}")
        logger.info("  Fetch interval (polling): %s", config.fetch_every)
    else:
        logger.info("  Automatic polling disabled (interval=%s)", config.fetch_every)

    lines.extend(
        _remote_tuning_lines(config, create_missing=True, replicate_hidden=False)
    )

    logger.info("  Git URL for replication: %s", git_url)

    # Fetch refspecs
    for ref in _sync_refspecs(config):
        lines.append(f"  fetch = {ref}")

    # Project filter
    if project:
        lines.append(f"  projects = {project}")

    # When meta-ref replication is on, the primary remote carries a
    # ``+refs/meta/*`` wildcard (appended above).  With an empty
    # ``project`` filter the primary remote replicates ALL projects
    # (including ``All-Projects`` and ``All-Users``); even with a
    # ``project`` filter set, an operator could write a pattern that
    # matches them.  In either case that wildcard could pull
    # ``All-Projects:refs/meta/config`` over the top of the deployed
    # container's locally-bootstrapped global ACL — the exact
    # Administrators-group hijack the magic-repo remote below goes to
    # great lengths to avoid.  The dedicated ``<slug>-meta`` remote is
    # the only path that should ever touch the magic projects (and it
    # enumerates NoteDb refs precisely so it never fetches
    # ``refs/meta/config``).  We therefore emit ``excludeProjects``
    # for both magic projects *unconditionally* whenever
    # ``replicate_meta_refs`` is enabled — independent of the
    # ``project`` filter — so the primary remote's wildcard can never
    # reach them.  The pull-replication plugin (a fork of the
    # ``replication`` plugin) supports ``excludeProjects`` for exactly
    # this: a project must match a ``projects`` pattern AND not match
    # any ``excludeProjects`` pattern to be replicated.
    if config.replicate_meta_refs:
        lines.append("  excludeProjects = All-Projects")
        lines.append("  excludeProjects = All-Users")

    return lines


def _magic_repo_remote_lines(
    slug: str,
    git_url: str,
    config: ActionConfig,
) -> list[str]:
    """Return the ``[remote "<slug>-meta"]`` section for the magic repos.

    Emits a second remote that targets Gerrit's ``All-Users`` and
    ``All-Projects`` repositories with the broader set of refspecs they
    need.  These are the "magic" projects that hold per-account
    identities, external IDs, group membership, the change-number
    sequence and global ACLs.  Without them, replicated changes display
    authors as "Gerrit Code Review", group ACLs do not resolve, and any
    new change uploaded against the CI Gerrit risks colliding with the
    source's change-number sequence.

    We use a distinct ``[remote "<slug>-meta"]`` section so the
    primary remote's project filter and per-project refspecs stay
    narrowly scoped to user projects.  ``createMissingRepositories``
    is set to ``false`` here because Gerrit always creates these
    special repos itself during ``gerrit init``.

    CRITICAL: refs/meta/config is INTENTIONALLY EXCLUDED.
    ====================================================
    An earlier version of this code used a blanket
    ``+refs/meta/*:refs/meta/*`` refspec for both magic projects.
    That pulled the source server's
    ``All-Projects:refs/meta/config`` over the top of the deployed
    container's locally-bootstrapped global ACL.  The fallout was
    silent but severe:

    * ``refs/meta/config`` on ``All-Projects`` is the
      server-wide ACL definition.  It names the UUID of the
      ``Administrators`` group, plus every per-ref permission
      block (read / push / submit / forge-author / etc.).
    * The bootstrap container creates account 1000000 and adds
      it to the *local* Administrators group (with a locally
      generated UUID).  Setup-gerrit-user.py then provisions the
      operator's SSH keys against that account.
    * After pull-replication writes the source server's
      ``refs/meta/config`` into the local All-Projects, the
      Administrators group reference resolves to the source
      server's UUID, whose membership is the source server's
      admins — NOT the local account 1000000.  Account 1000000
      still exists in ``refs/users/00/1000000`` (untouched
      because the ``refs/users/*`` fetch typically fails on
      ACL-restricted source servers), but it is no longer in
      any group with ``administrateServer`` capability.
    * Every REST endpoint that requires ``administrate-server``
      or ``maintain-server`` then returns 403 against the
      would-be admin.  ``POST /projects/<name>/index.changes``
      needs ``administrate-server``; ``POST /config/server/
      caches/<name>/flush`` needs ``maintain-server``.  Both
      of those calls fired 403 across the board in the
      2026-05-21 14:35 / 14:51 / 15:02 dispatches with the
      blanket-refspec config.
    * Operators see the symptom in the deployed Gerrit UI too:
      their account exists (DEVELOPMENT_BECOME_ANY_ACCOUNT
      still works) but the admin UI is locked because the
      Administrators group no longer points at them.

    Fix: enumerate the meta refs we actually need by exact name
    so the wildcard never grabs ``refs/meta/config``.  The
    specific refs we want are NoteDb-related (the things that
    actually let the deployed Gerrit render the source server's
    accounts / groups / changes correctly):

    * ``refs/meta/external-ids`` (All-Users) — login → account_id
      map; without this, replicated changes show ``Anonymous
      Coward`` instead of real author names.
    * ``refs/meta/group-names`` (All-Users) — group UUID → name
      map; without this, replicated group references render as
      raw UUIDs.
    * ``refs/meta/version`` (both) — NoteDb schema version pin;
      harmless to mirror and required for some consistency
      checks the secondary index runs.

    We do NOT enumerate ``refs/meta/config`` for either project
    because:
      - All-Projects:refs/meta/config = source's global ACL
        (the hijack risk above).
      - All-Users:refs/meta/config = source's All-Users-specific
        ACL; replicating it has the same hijack effect against
        account-edit / draft-comment permissions on the local
        deployment.
    """
    lines = [
        "",
        "# Magic-repo remote: All-Users / All-Projects NoteDb refs.",
        "# Required for accounts, external IDs, groups and the",
        "# change-number sequence to resolve on the deployed",
        "# CI Gerrit.  refs/meta/config is INTENTIONALLY",
        "# EXCLUDED — see the source comment in",
        "# generate_replication_config for the full rationale",
        "# (TL;DR: replicating it overwrites the local",
        "# Administrators-group ACL and breaks reindex /",
        "# cache-flush / admin UI on the bootstrap account).",
        f'[remote "{slug}-meta"]',
        f"  url = {git_url}",
    ]

    if config.fetch_every_enabled:
        lines.append(f"  fetchEvery = {config.fetch_every}")

    lines.extend(
        _remote_tuning_lines(config, create_missing=False, replicate_hidden=True)
    )
    lines.extend(
        [
            # Refspecs are enumerated rather than wildcarded so
            # the source server's ``refs/meta/config`` (on either
            # All-Projects or All-Users) is never pulled.  See the
            # docstring above for the rationale.  Each refspec
            # is documented inline so future maintainers can see
            # which magic project the ref normally lives on and
            # why we are mirroring it.
            #
            # NoteDb identity / membership refs (All-Users):
            "  fetch = +refs/users/*:refs/users/*",
            "  fetch = +refs/groups/*:refs/groups/*",
            "  fetch = +refs/meta/external-ids:refs/meta/external-ids",
            "  fetch = +refs/meta/group-names:refs/meta/group-names",
            # Per-user state refs (All-Users); harmless no-ops
            # against All-Projects because they don't exist there.
            "  fetch = +refs/draft-comments/*:refs/draft-comments/*",
            "  fetch = +refs/starred-changes/*:refs/starred-changes/*",
            # Change-number sequence (All-Projects); also a no-op
            # against All-Users.  Without this the local container
            # would start handing out change numbers from 1, which
            # would collide with the replicated refs/changes/*
            # numbers on the very first locally-uploaded change.
            # The test Gerrit is read-only by policy, so this is
            # belt-and-braces, but cheap to mirror.
            "  fetch = +refs/sequences/*:refs/sequences/*",
            # NoteDb schema-version pin (both projects).  Cheap to
            # mirror and helps some consistency-check paths in the
            # secondary index.
            "  fetch = +refs/meta/version:refs/meta/version",
            # Magic-project filter.  Both names are listed even
            # though some refspecs only apply to one of them —
            # the pull-replication plugin silently skips refs
            # that don't exist for a given project.
            "  projects = All-Users",
            "  projects = All-Projects",
        ]
    )

    logger.info(
        "  Meta-ref replication enabled: "
        "All-Users / All-Projects NoteDb refs will be mirrored "
        "(refs/meta/config excluded to preserve local ACL)"
    )

    return lines
